export const librosImportados = [
  {
    id: "1",
    nombre: "1984 - George Orwell",
    precio: 25,
    stock: 120,
    disponibilidad: "En stock",
    categorias: ["Distopía", "Ciencia ficción", "Política"],
  },
  {
    id: "2",
    nombre: "El Señor de los Anillos: La Comunidad del Anillo - J.R.R. Tolkien",
    precio: 45,
    stock: 40,
    disponibilidad: "Poco stock",
    categorias: ["Fantasía", "Aventura", "Clásico"],
  },
  {
    id: "3",
    nombre: "Harry Potter y la Piedra Filosofal - J.K. Rowling",
    precio: 30,
    stock: 0,
    disponibilidad: "Agotado",
    categorias: ["Fantasía", "Juvenil", "Magia"],
  },
  {
    id: "4",
    nombre: "Cien Años de Soledad - Gabriel García Márquez",
    precio: 35,
    stock: 75,
    disponibilidad: "En stock",
    categorias: ["Realismo mágico", "Clásico", "Latinoamericano"],
  },
  {
    id: "5",
    nombre: "El Principito - Antoine de Saint-Exupéry",
    precio: 20,
    stock: 200,
    disponibilidad: "En stock",
    categorias: ["Fábula", "Filosofía", "Infantil"],
  },
  {
    id: "6",
    nombre: "Orgullo y Prejuicio - Jane Austen",
    precio: 28,
    stock: 35,
    disponibilidad: "Poco stock",
    categorias: ["Romance", "Clásico", "Costumbrismo"],
  },
  {
    id: "7",
    nombre: "Fahrenheit 451 - Ray Bradbury",
    precio: 27,
    stock: 15,
    disponibilidad: "Poco stock",
    categorias: ["Distopía", "Ciencia ficción", "Crítica social"],
  },
  {
    id: "8",
    nombre: "Crimen y Castigo - Fiódor Dostoyevski",
    precio: 33,
    stock: 0,
    disponibilidad: "Agotado",
    categorias: ["Psicológico", "Clásico", "Drama"],
  },
  {
    id: "9",
    nombre: "Dune - Frank Herbert",
    precio: 40,
    stock: 65,
    disponibilidad: "En stock",
    categorias: ["Ciencia ficción", "Aventura", "Épico"],
  },
  {
    id: "10",
    nombre: "Los Juegos del Hambre - Suzanne Collins",
    precio: 32,
    stock: 110,
    disponibilidad: "En stock",
    categorias: ["Distopía", "Acción", "Juvenil"],
  },
];
