-- \l LISTAMOS LAS BASES DE DATOS

CREATE DATABASE tutorias_g99;

-- \c CONECTAMOS A LA BASE DE DATOS
-- TODOS LOS COMANDOS QUE COMIENZAN CON \ SON COMANDOS DE LA CONSOLA DE POSTGRESQL POR LO TANTO NO NECESITAN UN ; AL FINAL

-- \dt LISTAMOS LAS TABLAS

CREATE TABLE usuarios (id SERIAL, nombre VARCHAR, edad INTEGER);

CREATE TABLE productos (id SERIAL, titulo VARCHAR(50), precio FLOAT);

INSERT INTO usuarios (nombre, edad) VALUES ('Ivan', 27);
INSERT INTO usuarios (nombre, edad) VALUES ('Maria', 20);

SELECT * FROM usuarios;

SELECT nombre FROM usuarios;

SELECT * FROM usuarios WHERE edad > 21; -- LA CLASULA WHERE NOS PERMITE FILTRAR RESULTADOS CON CONDICIONES 
SELECT * FROM usuarios WHERE edad > 21 AND nombre = 'Ivan' AND id = 1;
-- PODEMOS ANIDAR CONDICIONES CON AND 

SELECT * FROM usuarios WHERE edad = 20 OR edad = 27;
-- PODEMOS ANIDAR CONDICIONES CON OR

SELECT * FROM usuarios LIMIT 3;

-- CON LIMIT PODEMOS LIMITAR LA CANTIDAD DE RESULTADOS QUE QUEREMOS OBTENER SIEMPRE SE COLOCA AL FINAL 

SELECT * FROM usuarios ORDER BY edad ASC;
SELECT * FROM usuarios ORDER BY edad DESC;

-- CON ORDER BY PODEMOS ORDENAR LOS RESULTADOS POR UNA COLUMNA EN PARTICULAR, PODEMOS USAR ASC PARA ORDENAR DE FORMA ASCENDENTE Y DESC PARA ORDENAR DE FORMA DESCENDENTE (PODEMOS USARLO TAMBIEN EN FECHAS Y OTROS TIPOS DE DATOS)

SELECT * FROM usuarios WHERE edad > 20 ORDER BY edad ASC LIMIT 3;
-- PODEMOS COMBINAR VARIAS CLAUSULAS EN UNA SOLA CONSULTA



-- NOTA MUY IMPORTANTE: SIEMPRE QUE USEMOS UPDATE O DELETE DEBEMOS USAR LA CLAUSULA WHERE PARA ESPECIFICAR QUE REGISTROS QUEREMOS MODIFICAR O ELIMINAR, SI NO LO HACEMOS SE MODIFICARAN O ELIMINARAN TODOS LOS REGISTROS DE LA TABLA


UPDATE usuarios SET edad = 40 WHERE id = 3;
-- CON UPDATE PODEMOS MODIFICAR REGISTROS EXISTENTES, USAMOS LA CLAUSULA WHERE PARA ESPECIFICAR QUE REGISTROS QUEREMOS MODIFICAR

DELETE FROM usuarios WHERE id = 3;

-- CON DELETE PODEMOS ELIMINAR REGISTROS EXISTENTES, USAMOS LA CLAUSULA WHERE PARA ESPECIFICAR QUE REGISTROS QUEREMOS ELIMINAR

DROP TABLE productos;
-- CON DROP TABLE PODEMOS ELIMINAR TABLAS COMPLETAS

DROP DATABASE xxxxxxxx;

-- CON DROP DATABASE PODEMOS ELIMINAR BASES DE DATOS COMPLETAS


ALTER TABLE usuarios ADD COLUMN email VARCHAR(80);
-- CON ALTER TABLE PODEMOS MODIFICAR LA ESTRUCTURA DE UNA TABLA, EN ESTE CASO AGREGAMOS UNA COLUMNA NUEVA

ALTER TABLE usuarios DROP COLUMN email;
-- CON ALTER TABLE PODEMOS MODIFICAR LA ESTRUCTURA DE UNA TABLA, EN ESTE CASO ELIMINAMOS UNA COLUMNA

